services:
  db:
    container_name: simple-pastebin-db
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'simple_pastebin'
      POSTGRES_USER: 'paster'
      POSTGRES_PASSWORD: 'paster_password'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
