export const PASTE_TYPEORM_REPOSITORY = 'PASTE_TYPEORM_REPOSITORY';
export const TYPEORM_DATA_SOURCE = 'TYPEORM_DATA_SOURCE';
// export const PASTE_REDIS_REPOSITORY = 'PASTE_REDIS_REPOSITORY';
// export const REDIS_DATA_SOURCE = 'REDIS_DATA_SOURCE';
